# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk-node-browsers

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/project

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v6-dependencies-{{ checksum "editor/package.json" }}--{{ checksum "editor/deps.edn"}}

      - run:
          name: Install Clojure, via curl
          command: curl -O https://download.clojure.org/install/linux-install-1.9.0.358.sh && chmod +x linux-install-1.9.0.358.sh && sudo ./linux-install-1.9.0.358.sh

      - run:
          name: Install JavaScript dependencies, via NPM
          command: npm install;
          working_directory: ~/project/editor

      - run:
          name: Compile Styles, via webpack
          command: npx webpack -p;
          working_directory: ~/project/editor

      - run:
          name: Compute Classpath, via clj
          command: clojure -Spath
          working_directory: ~/project/editor

      - run:
          name: Compile ClojureScript, via shadow-cljs
          command: npm run release;
          working_directory: ~/project/editor

      - run:
          name: Deploy, via Firebase
          command: npm run deploy;
          working_directory: ~/project/editor

      - run:
          name: Log Shadow-CLJS logs on Error
          command: cat target/shadow-cljs/shadow-cljs.log.0 2> /dev/null
          working_directory: ~/project/editor
          when: on_fail
      - run:
          name: Log Firebase logs on Error
          command: cat firebase-debug.log 2> /dev/null
          working_directory: ~/project/editor
          when: on_fail
      - save_cache:
          paths:
            - ~/project/editor/node_modules
            - ~/project/editor/target
            - ~/project/editor/.shadow-cljs
            - ~/project/editor/.cpcache
            - ~/.m2
            - ~/.clojure/.cpcache
          key: v6-dependencies-{{ checksum "editor/package.json" }}--{{ checksum "editor/deps.edn"}}


